bounds:
  ais.gbar_nax: !!python/tuple
  - 0.02
  - 0.5
  ais.gkmbar: !!python/tuple
  - 0.00005
  - 0.05
  ais.sha_nax: !!python/tuple
  - -6.0
  - -1.0
  axon.gbar_nax: !!python/tuple
  - 0.02
  - 0.1
  axon.gkabar: !!python/tuple
  - 0.001
  - 0.05
  soma.gtcabar: !!python/tuple
  - 5.0E-7
  - 2.0E-02
  soma.gncabar: !!python/tuple
  - 5.0E-7
  - 2.0E-02
  soma.glcabar: !!python/tuple
  - 5.0E-7
  - 2.0E-02
  soma.gbkbar: !!python/tuple
  - 5.0E-08
  - 1.0E-03
  soma.gskbar: !!python/tuple
  - 5.0E-08
  - 1.0E-03
  soma.gbar_nas: !!python/tuple
  - 0.01
  - 0.05
  soma.gkabar: !!python/tuple
  - 0.005
  - 0.075
  soma.gkdrbar: !!python/tuple
  - 0.001
  - 0.075
  axon.gkdrbar: !!python/tuple
  - 0.001
  - 0.075
  soma.sh_nas/x: !!python/tuple
  - 1.0
  - 8.0
  soma.tau_Cacum: !!python/tuple
  - 9.
  - 100.
default_params:
rel_bounds:
- - axon.gbar_nax
  - '>'
  - 1.0
  - soma.gbar_nas
- - ais.gbar_nax
  - '>'
  - 2.0
  - axon.gbar_nax
- - axon.gkabar
  - '<'
  - 1.0
  - soma.gkabar
- - axon.gkdrbar
  - '>='
  - 1.0
  - soma.gkdrbar
feature_names:
#- dend R_inp
#- term_dend R_inp
- soma R_inp
#- soma R_inp (no h)
- soma vm_rest
#- soma vm_rest (no h)
- vm_th
- ADP
- fAHP
- mAHP
- rebound_firing
- vm_stability
- ais_delay
- slow_depo
- rheobase
- soma_spike_amp
- f_I_log10_slope
- spike_adi_slope
- spike_detector_delay
update_context:
- - optimize_DG_BC_spiking
  - reset_biophysics
- - optimize_DG_BC_spiking
  - update_mechanisms_spiking
get_features_stages:
- source: optimize_DG_BC_spiking
  get_args_dynamic: get_args_dynamic_i_holding
  compute_features: compute_features_spike_shape
- source: optimize_DG_BC_spiking
  get_args_dynamic: get_args_dynamic_fI
  compute_features: compute_features_fI
  filter_features: filter_features_fI
get_objectives:
  optimize_DG_BC_spiking: get_objectives_spiking
kwargs:
  mech_file_path: mechanisms/20181127_DG_MC_only_leak_mech.yaml  # 20180905_DG_MC_excitability_mech.yaml
  gid: 1039000
  cell_type: BC
  correct_for_spines: False
  verbose: 2
  daspk: True  # False
  cvode: False
  config_file: Small_Scale_Control_BC.yaml 
  template_paths: ../DGC/Mateos-Aparicio2014:../dentate/templates
  hoc_lib_path: ../dentate
  config_prefix: ../dentate/config
  dataset_prefix: ../dentate/datasets
  results_path: data
  km_mech_name: DGC_KM
objective_names:
- vm_th
- ADP
- fAHP
- rebound_firing
- vm_stability
- ais_delay
- slow_depo
- spike_adaptation_residuals
- f_I_residuals
optimization_title: DG_BC_spiking
param_gen: PopulationAnnealing
param_names:
- soma.gbar_nas
- axon.gbar_nax
- ais.gbar_nax
- soma.gkabar
- soma.gkdrbar
- axon.gkabar
- axon.gkdrbar
- soma.sh_nas/x
- ais.sha_nax
- soma.gtcabar
- soma.gncabar
- soma.glcabar
- soma.gbkbar
- soma.gskbar
- ais.gkmbar
- soma.tau_Cacum
target_range:
  ADP: 0.05
  fAHP: 0.07
  ais_delay: 0.0005
  rebound_firing: 0.002
  vm_th: 0.01
  vm_stability: 0.5
  spike_rate: 0.1
  slow_depo: 0.1
target_val:
#  term_dend R_inp: 1000.
#  dend R_inp: 117.
#  soma R_inp: 43.0 
#  soma R_inp (no h): 144.
  soma vm_rest: -62.0
#  soma vm_rest (no h): -70.0
  min_ADP: 1.
  max_ADP: 10.
  min_fAHP: -24.9 
  max_fAHP: -14.9
  ais_delay: 0.0
  rebound_firing: 0
  max_slow_depo: 5.0
  min_slow_depo: -1.0
  vm_th: -40.0
  vm_stability: 5.0
x0:
  soma.tau_Cacum: 4.411152E+01
  soma.gkdrbar: 4.193310E-02
  axon.gkabar: 1.914911E-02
  ais.sha_nax: -3.931174E+00
  axon.gkdrbar: 6.831896E-02
  soma.sh_nas/x: 7.197155E+00
  ais.gbar_nax: 4.097186E-01
  axon.gbar_nax: 4.272765E-02
  soma.gbar_nas: 1.794131E-02
  soma.gtcabar: 0.0002625
  soma.gncabar: 0.002
  soma.glcabar: 0.01
  soma.gbkbar: 0.00009
  soma.gskbar: 0.0001
  ais.gkmbar: 2.584361E-04
  soma.gkabar: 3.166313E-02
