bounds:
  soma.g_pas: !!python/tuple
  - 1.0E-12
  - 1.0E-7
feature_names:
- i_syn_amp
update_context:
- - optimize_DG_MC_iEPSP_propagation
  - reset_biophysics
get_features_stages:
- source: optimize_DG_MC_iEPSP_propagation
  get_args_dynamic: get_args_dynamic_iEPSP_unit_optimize 
  compute_features: compute_features_iEPSP_i_unit 
- source: optimize_DG_MC_iEPSP_propagation
  get_args_dynamic: get_args_dynamic_iEPSP_unit 
  compute_features: compute_features_iEPSP_i_unit 
  filter_features: filter_features_attenuation
get_objectives:
  optimize_DG_MC_iEPSP_propagation: get_objectives_iEPSP_attenuation 
kwargs:
  mech_file_path: mechanisms/20191029_DG_MC_excitability_mech.yaml
  gid: 1000000
  cell_type: MC
  correct_for_spines: False 
  verbose: 2
  daspk: True 
  config_file: Small_Scale_Control_MC_BC.yaml
  template_paths: ../DGC/Mateos-Aparicio2014:../dentate/templates
  hoc_lib_path: ../dentate
  config_prefix: ../dentate/config
  dataset_prefix: ../dentate/datasets
  results_path: data
objective_names:
- iEPSP_attenuation_residual
optimization_title: DG_MC_iEPSP_propagation
param_gen: PopulationAnnealing
param_names:
- soma.g_pas
target_range:
target_val:
  iEPSP_unit_amp: 1.
  iEPSP_attenuation_short: 0.17
  iEPSP_attenuation_long: 0.23
x0:
  soma.g_pas: 1.050E-10
