bounds:
  E_FF_mean_weight: !!python/tuple
    - 0.1
    - 5.
  E_E_mean_weight: !!python/tuple
    - 0.1
    - 5.
  E_I_mean_weight: !!python/tuple
    - 0.1
    - 5.
  I_FF_mean_weight: !!python/tuple
    - 0.1
    - 5.
  I_E_mean_weight: !!python/tuple
    - 0.1
    - 5.
  I_I_mean_weight: !!python/tuple
    - 0.1
    - 5.
  E_FF_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  E_E_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  E_I_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  I_FF_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  I_E_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  I_I_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  E_E_tau_offset: !!python/tuple
    - 2.
    - 20.
  E_I_tau_offset: !!python/tuple
    - 2.
    - 30.
  I_E_tau_offset: !!python/tuple
    - 2.
    - 20.
  I_I_tau_offset: !!python/tuple
    - 2.
    - 30.
  E_E_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  E_E_FF_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  I_E_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  I_E_FF_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  E_norm_syn_count: !!python/tuple
    - 0.1
    - 1.
  I_norm_syn_count: !!python/tuple
    - 0.1
    - 1.
rel_bounds:
#- - E_FF_mean_weight
#  - '<'
#  - 2.0
#  - E_E_mean_weight
#- - E_FF_mean_weight
#  - '>'
#  - 0.5
#  - E_E_mean_weight
#- - I_FF_mean_weight
#  - '<'
#  - 2.0
#  - I_E_mean_weight
#- - I_FF_mean_weight
#  - '>'
#  - 0.5
#  - I_E_mean_weight
feature_names:
- E_mean_peak_rate
- E_mean_min_rate
- I_mean_active_rate
- FF_frac_active
- E_frac_active
- I_frac_active
- FF_theta_envelope_ratio
- E_theta_envelope_ratio
- I_theta_envelope_ratio
- FF_gamma_envelope_ratio
- E_gamma_envelope_ratio
- I_gamma_envelope_ratio
- E_centroid_theta_freq
- I_centroid_theta_freq
- E_centroid_gamma_freq
- I_centroid_gamma_freq
- E_theta_tuning_index
- I_theta_tuning_index
- E_gamma_tuning_index
- I_gamma_tuning_index
update_context:
- - optimize_simple_network
  - update_context
get_features_stages:
- source: optimize_simple_network
  compute_features: compute_features
get_objectives:
  optimize_simple_network: get_objectives
kwargs:
  verbose: 1
  connection_seed: 30000000
  spikes_seed: 130000000
  weights_seed: 230000000
  tuning_seed: 430000000
  connectivity_type: uniform
  default_weight_distribution_type: normal
  connection_weight_distribution_types:
    E:
      FF: lognormal
      E: lognormal
  input_types:
    FF: gaussian
  input_max_rates:
    FF: 20.
  input_min_rates:
    FF: 0.
  input_norm_tuning_widths:
    FF: 0.5
  pop_cell_types:
    FF: input
    E: IB
    I: FS
  pop_sizes:
    FF: 1000
    E: 1000
    I: 200
  default_syn_mech_params:
    I:
      FF:
        g_unit: 0.0001925
      E:
        g_unit: 0.0001925
      I:
        g_unit: 0.0001925
    E:
      FF:
        g_unit: 0.0005275
      E:
        g_unit: 0.0005275
      I:
        g_unit: 0.0005275
objective_names:
- E_mean_peak_rate
- E_mean_min_rate
- I_mean_active_rate
- E_frac_active
- I_frac_active
- E_theta_envelope_ratio
- I_theta_envelope_ratio
- E_gamma_envelope_ratio
- I_gamma_envelope_ratio
- E_centroid_theta_freq
- I_centroid_theta_freq
- E_centroid_gamma_freq
- I_centroid_gamma_freq
- E_theta_tuning_index
- I_theta_tuning_index
- E_gamma_tuning_index
- I_gamma_tuning_index
optimization_title: simple_network_C
param_gen: PopulationAnnealing
param_names:
- E_FF_mean_weight
- E_E_mean_weight
- E_I_mean_weight
- I_FF_mean_weight
- I_E_mean_weight
- I_I_mean_weight
- E_FF_weight_norm_sigma
- E_E_weight_norm_sigma
- E_I_weight_norm_sigma
- I_FF_weight_norm_sigma
- I_E_weight_norm_sigma
- I_I_weight_norm_sigma
- E_E_tau_offset
- E_I_tau_offset
- I_E_tau_offset
- I_I_tau_offset
- E_E_syn_proportion
- E_E_FF_syn_proportion
- I_E_syn_proportion
- I_E_FF_syn_proportion
- E_norm_syn_count
- I_norm_syn_count
target_range:
  E_mean_peak_rate: 0.1
  E_mean_min_rate: 0.1
  I_mean_active_rate: 0.1
  E_frac_active: .001
  I_frac_active: .001
  E_theta_envelope_ratio: .01
  I_theta_envelope_ratio: .01
  E_gamma_envelope_ratio: .01
  I_gamma_envelope_ratio: .01
  E_centroid_theta_freq: 0.05
  I_centroid_theta_freq: 0.05
  E_centroid_gamma_freq: 0.5
  I_centroid_gamma_freq: 0.5
  E_theta_tuning_index: 0.2
  I_theta_tuning_index: 0.2
  E_gamma_tuning_index: 0.2
  I_gamma_tuning_index: 0.2
target_val:
  E_mean_peak_rate: 20.
  E_mean_min_rate: 0.
  I_mean_active_rate: 20.
  E_frac_active: .6
  I_frac_active: .9
  E_theta_envelope_ratio: .5
  I_theta_envelope_ratio: .5
  E_gamma_envelope_ratio: .25
  I_gamma_envelope_ratio: .25
  E_centroid_theta_freq: 7.
  I_centroid_theta_freq: 7.
  E_centroid_gamma_freq: 70.
  I_centroid_gamma_freq: 70.
  E_theta_tuning_index: 5.
  I_theta_tuning_index: 5.
  E_gamma_tuning_index: 5.
  I_gamma_tuning_index: 5.
x0:
  E_I_weight_norm_sigma: 3.133021E-01
  E_E_FF_syn_proportion: 8.959412E-01
  E_I_tau_offset: 4.076602E+00
  E_E_weight_norm_sigma: 3.283792E-01
  I_E_FF_syn_proportion: 7.391833E-01
  E_E_tau_offset: 5.549544E+00
  I_FF_mean_weight: 2.393251E+00
  E_E_mean_weight: 2.881852E+00
  E_FF_weight_norm_sigma: 9.257900E-01
  E_I_mean_weight: 1.131226E-01
  I_E_weight_norm_sigma: 5.487550E-01
  I_E_tau_offset: 1.750748E+01
  I_I_weight_norm_sigma: 5.282017E-01
  I_E_syn_proportion: 9.759795E-02
  I_FF_weight_norm_sigma: 7.706212E-01
  E_E_syn_proportion: 3.916749E-01
  I_I_mean_weight: 2.311584E+00
  E_FF_mean_weight: 1.697106E+00
  I_E_mean_weight: 4.106105E+00
  I_I_tau_offset: 3.438833E+00
  E_norm_syn_count: .1
  I_norm_syn_count: .1
