bounds:
  soma.g_pas: !!python/tuple
  - 1.0E-12
  - 1.0E-4
feature_names:
- i_EPSC
update_context:
- - optimize_DG_MC_iEPSP_propagation
  - reset_biophysics
get_features_stages:
- source: optimize_DG_MC_iEPSP_propagation
  get_args_dynamic: get_args_dynamic_i_EPSC
  compute_features: compute_features_iEPSP_i_unit
- source: optimize_DG_MC_iEPSP_propagation
  get_args_dynamic: get_args_dynamic_iEPSP_unit
  compute_features: compute_features_iEPSP_i_unit
  filter_features: filter_features_iEPSP_attenuation
get_objectives:
  optimize_DG_MC_iEPSP_propagation: get_objectives_iEPSP_attenuation
kwargs:
  mech_file_path: mechanisms/20200511_0641_DG_MC_leak_spiking_mech.yaml
  max_i_EPSP_attenuation_distance: 300.
  gid: 1000000
  cell_type: MC
  correct_for_spines: False
  verbose: 2
  daspk: True
  cvode: False
  config_file: Small_Scale_Control_MC_BC_shortdendnewtermdim.yaml
  template_paths: ../DGC/Mateos-Aparicio2014:../dentate/templates
  hoc_lib_path: ../dentate
  config_prefix: ../dentate/config
  dataset_prefix: ../dentate/datasets
  results_path: data
objective_names:
- iEPSP_attenuation_residual
optimization_title: DG_MC_iEPSP_propagation
param_gen: PopulationAnnealing
param_names:
- soma.g_pas
target_range:
  iEPSP_attenuation: 0.001
target_val:
  iEPSP_unit_amp: 1.
x0:
  soma.g_pas: 1.050E-10
