bounds:
  dend.g_pas slope:
  - 1.0E-9
  - 1.0E-4
  dend.g_pas tau:
  - 25.
  - 400.
  soma.g_pas:
  - 1.0E-12
  - 1.0E-7
  e_pas:
  - -77.0
  - -70.0
  ais.gbar_nax:
  - 0.02
  - 0.5
  ais.gkmbar:
  - 0.00005
  - 0.05
  ais.sha_nax:
  - -6.0
  - -1.0
  axon.gbar_nax:
  - 0.02
  - 0.1
  axon.gkabar:
  - 0.001
  - 0.05
  dend.gbar_nas:
  - 0.01
  - 0.05
  dend.gbar_nas min:
  - 0.0
  - 0.05
  dend.gkabar:
  - 0.001
  - 0.25
  soma.gCa factor:
  - 0.005
  - 2.0
  soma.gCadepK factor:
  - 0.0005
  - 10.
  soma.gbar_nas:
  - 0.01
  - 0.05
  soma.gkabar:
  - 0.005
  - 0.075
  soma.gkdrbar:
  - 0.001
  - 0.075
  axon.gkdrbar:
  - 0.001
  - 0.075
  dend.gkdrbar:
  - 0.0005
  - 0.01
  soma.sh_nas/x:
  - 1.0
  - 8.0
  soma.tau_Cacum:
  - 9.
  - 100.
  AMPA.tau:
  - 50.
  - 400.
  AMPA.slope:
  - 1.0e-7
  - 1.0e-5
  AMPA.g0:
  - 1.0e-4
  - 0.001
  NMDA.g_unit:
  - 1.0e-5
  - 5.0e-3
  NMDA.gamma:
  - 0.02
  - 0.15
  NMDA.Kd:
  - 3.
  - 12.
  NMDA.vshift:
    - -40.
    - 0.
default_params:
rel_bounds:
- - dend.gbar_nas
  - '<='
  - 1.0
  - soma.gbar_nas
- - dend.gbar_nas min
  - '<='
  - 1.0
  - dend.gbar_nas
- - axon.gbar_nax
  - '>'
  - 1.0
  - soma.gbar_nas
- - ais.gbar_nax
  - '>'
  - 2.0
  - axon.gbar_nax
- - dend.gkabar
  - '>'
  - 1.0
  - soma.gkabar
- - axon.gkabar
  - '<'
  - 1.0
  - soma.gkabar
- - axon.gkdrbar
  - '>='
  - 1.0
  - soma.gkdrbar
- - dend.gkdrbar
  - '<'
  - 1.0
  - soma.gkdrbar
- - NMDA.g_unit
  - '<'
  - 2.0
  - AMPA.g0
feature_names:
- dend R_inp
- term_dend R_inp
- soma R_inp
- soma vm_rest
- vm_th
- ADP
- fAHP
- mAHP
- rebound_firing
- vm_stability
- ais_delay
- slow_depo
- dend_bAP_ratio
- rheobase
- soma_spike_amp
- f_I_slope
- dend_spike_amp
- i_EPSC
- spike_detector_delay
- mean_unitary_EPSP_amp
- mean_NMDA_contribution
- integration_gain_control
- integration_gain_AP5
- initial_gain_control
- initial_gain_AP5
update_context:
- source: optimize_DG_GC_leak
  function: reset_biophysics
- source: optimize_DG_GC_leak
  function: update_mechanisms_leak
- source: optimize_DG_GC_spiking
  function: update_mechanisms_spiking
- source: optimize_DG_GC_synaptic_integration
  function: reset_syn_mechanisms
- source: optimize_DG_GC_synaptic_integration
  function: update_syn_mechanisms
stages:
- source: optimize_DG_GC_leak
  get_args_static: get_args_static_leak
  compute_features: compute_features_leak
  get_objectives: get_objectives_leak
- source: optimize_DG_GC_spiking
  get_args_dynamic: get_args_dynamic_i_holding
  compute_features: compute_features_spike_shape
- source: optimize_DG_GC_spiking
  get_args_dynamic: get_args_dynamic_fI
  compute_features: compute_features_fI
  filter_features: filter_features_fI
- source: optimize_DG_GC_spiking
  get_args_dynamic: get_args_dynamic_spike_adaptation
  compute_features: compute_features_spike_adaptation
- source: optimize_DG_GC_spiking
  get_args_dynamic: get_args_dynamic_dend_spike
  compute_features: compute_features_dend_spike
  filter_features: filter_features_dend_spike
  get_objectives: get_objectives_spiking
- source: optimize_DG_GC_iEPSP_propagation
  get_args_dynamic: get_args_dynamic_i_EPSC
  compute_features: compute_features_iEPSP_i_unit
- source: optimize_DG_GC_iEPSP_propagation
  get_args_dynamic: get_args_dynamic_iEPSP_unit
  compute_features: compute_features_iEPSP_i_unit
  filter_features: filter_features_iEPSP_attenuation
  get_objectives: get_objectives_iEPSP_attenuation
- source: optimize_DG_GC_synaptic_integration
  get_args_static: get_args_static_unitary_EPSP_amp
  compute_features: compute_features_unitary_EPSP_amp
  collective: export_unitary_EPSP_traces
- source: optimize_DG_GC_synaptic_integration
  get_args_static: get_args_static_compound_EPSP_amp
  compute_features: compute_features_compound_EPSP_amp
  collective: export_compound_EPSP_traces
  get_objectives: get_objectives_synaptic_integration
kwargs:
  mech_file_path: mechanisms/20181205_DG_GC_excitability_mech.yaml
  max_i_EPSP_attenuation_distance: 300.
  gid: 0
  cell_type: GC
  correct_for_spines: True
  verbose: 1
  seed_offset: 14e6
  daspk: False
  config_file: Small_Scale_Control_tune_GC_synapses.yaml  # Small_Scale_Control_LN_weights_Sat.yaml
  template_paths: ../DGC/Mateos-Aparicio2014:../dentate/templates
  hoc_lib_path: ../dentate
  config_prefix: ../dentate/config
  dataset_prefix: ../dentate/datasets
  results_path: data
  cache_queries: True
  debug: False  # True
  load_edges: True
  set_edge_delays: False
objective_names:
- dend R_inp
- term_dend R_inp
- soma R_inp
- soma vm_rest
- vm_th
- ADP
- fAHP
- rebound_firing
- vm_stability
- ais_delay
- slow_depo
- dend_bAP_ratio
- spike_adaptation_residuals
- f_I_residuals
- dend_spike_score
- iEPSP_attenuation_residual
- mean_unitary_EPSP_amp_residuals
- mean_NMDA_contribution_residuals
- integration_gain_control_residuals
- integration_gain_AP5_residuals
# - initial_gain_control_residuals
# - initial_gain_AP5_residuals
optimization_title: DG_GC_excitability_synint_combined
target_range:
  dend R_inp: 1.
  soma R_inp: 0.5
  soma vm_rest: 0.1
  ADP: 0.05
  fAHP: 0.07
  ais_delay: 0.0005
  dend_bAP_ratio: 0.0002
  rebound_firing: 0.002
  vm_th: 0.01
  vm_stability: 0.1
  dend_spike_amp: 0.1
  iEPSP_attenuation: 0.001
  mean_unitary_EPSP_amp: 0.005
  mean_NMDA_contribution: 0.001
  integration_gain_control: 0.005
  integration_gain_AP5: 0.005
  initial_gain_control: 0.005
  initial_gain_AP5: 0.005
target_val:
  term_dend R_inp: 1000.
  dend R_inp: 275.
  soma R_inp: 295.
  soma vm_rest: -77.0
  min_ADP: 0.
  max_ADP: 10.
  min_fAHP: 3.0
  max_fAHP: 15.
  ais_delay: 0.0
  dend_bAP_ratio: 0.5  # At ~100 uM from soma
  rebound_firing: 0
  slow_depo: 5.0
  vm_th: -48.0
  vm_stability: 5.0
  dend_spike_amp: 15.
  iEPSP_unit_amp: 1.
  mean_unitary_EPSP_amp: 0.6
  mean_NMDA_contribution: 0.2
  integration_gain_control: 1.38
  integration_gain_AP5: 0.8
  initial_gain_control: 1.
  initial_gain_AP5: 1.
x0:
  AMPA.g0: 2.830316E-04
  AMPA.slope: 1.801176E-06
  AMPA.tau: 2.745544E+02
  NMDA.Kd: 9.98
  NMDA.g_unit: 5.180688E-04
  NMDA.gamma: 0.11
  NMDA.vshift: -28.
  ais.gbar_nax: 4.412620E-01
  ais.gkmbar: 9.402899E-03
  ais.sha_nax: -4.897933E+00
  axon.gbar_nax: 7.628776E-02
  axon.gkabar: 1.037209E-02
  axon.gkdrbar: 6.995454E-02
  dend.g_pas slope: 1.501397E-05
  dend.g_pas tau: 2.438052E+02
  dend.gbar_nas: 2.947238E-02
  dend.gbar_nas min: 7.310450E-03
  dend.gkabar: 1.277488E-01
  dend.gkdrbar: 8.337353E-03
  e_pas: -7.239023E+01
  soma.gCa factor: 4.881511E-01
  soma.gCadepK factor: 6.505431E+00
  soma.g_pas: 1.836953E-08
  soma.gbar_nas: 3.448583E-02
  soma.gkabar: 2.300779E-02
  soma.gkdrbar: 4.935162E-02
  soma.sh_nas/x: 7.874204E+00
  soma.tau_Cacum: 6.155919E+01
